name: CD - Backend Services (Simulated)

on:
  workflow_dispatch:

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Simulated Backend Deployment
        run: |
          echo "Simulated deploy: Backend Infrastructure (ConfigMaps, Secrets, Databases)"
          echo "Simulated deploy: Backend Microservices (Product, Order)"
          echo "Simulated: Assigned Product Service IP = 10.0.0.101"
          echo "Simulated: Assigned Order Service IP = 10.0.0.102"

      - name: Capture Simulated Product IP
        id: capture_product
        run: echo "external_ip=10.0.0.101" >> $GITHUB_OUTPUT

      - name: Capture Simulated Order IP
        id: capture_order
        run: echo "external_ip=10.0.0.102" >> $GITHUB_OUTPUT
