name: CD - Deploy Frontend (Simulated)

on:
  workflow_dispatch:

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Simulated Frontend Deployment
        run: |
          echo "Simulated deploy: Frontend Application"
          echo "Simulated: Frontend Service available at http://10.0.0.200"
